#
#    Copyright (c) 2020 Project CHIP Authors
#    Copyright (c) 2018 Google LLC
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

#
# Makefile for building CHIP OSAL library and tests in isolation.
#
# Usage:
#   make -f Makefile.mk          # Build a local POSIX (linux or darwin) version of tests
#   make -f Makefile.mk test     # Build and run all tests
#   make -f Makefile.mk clean    # Clean up all built code, tests, and dependecies
#
#   # Build FreeRTOS version of tests (for nRF52840)
#   DEBUG=1 V=1 PLATFORM=nrf52840 make -f Makefile.mk
#

PROJ_ROOT ?= ..

### ===== Platforms =====

# Map supported platforms to dedicated build scripts

ifeq ($(PLATFORM),nrf52840)
include Makefile.freertos-nrf52840
endif

### ===== Host System Variants =====

# Default to PLATFORM=posix if no platform was specified
PLATFORM ?= posix

# Hook to allow platforms to add helpers for alternate output targets like .hex
TARGET_EXT ?= exe

ifeq ($(PLATFORM),posix)
TARGET_OSAL ?= posix

# Linux-specific POSIX build
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
TARGET_LDFLAGS = -lpthread -lstdc++ -lrt
endif

# Darwin-specific POSIX build
ifeq ($(UNAME_S),Darwin)
TARGET_LDFLAGS = -lpthread -lstdc++
endif

endif # PLATFORM == posix

### ===== Toolchain =====

CROSS_COMPILE ?=

ifeq ($(UNAME_S),Darwin)
CC  = ccache $(CROSS_COMPILE)clang
CPP = ccache $(CROSS_COMPILE)clang++
LD  = $(CROSS_COMPILE)clang++
AR  = $(CROSS_COMPILE)ar
else
CC  = ccache $(CROSS_COMPILE)gcc
CPP = ccache $(CROSS_COMPILE)g++
LD  = $(CROSS_COMPILE)g++
AR  = $(CROSS_COMPILE)ar
endif


### ===== Compiler Flags =====

INCLUDES =                                            \
    -I.                                               \
    -I$(PROJ_ROOT)/include                            \
    -I$(PROJ_ROOT)/targets/$(TARGET_OSAL)             \
    $(TARGET_INCLUDES)                                \
    $(NULL)

DEBUG ?= 0

DEFINES =                   \
    -DDEBUG=${DEBUG}        \
    -D_GNU_SOURCE           \
    $(NULL)

CFLAGS =                    \
    $(INCLUDES) $(DEFINES)  \
    $(TARGET_CCFLAGS)       \
    $(NULL)

LDFLAGS = $(TARGET_LDFLAGS)

ifeq ($(DEBUG),1)
CFLAGS += -g -O0
else
CFLAGS += -Os
endif


### ===== Sources =====

OSAL_PATH = $(PROJ_ROOT)/targets/$(TARGET_OSAL)

SRCS  = $(shell find $(OSAL_PATH) -maxdepth 1 -name '*.c')
SRCS += $(shell find $(OSAL_PATH) -maxdepth 1 -name '*.cc')
SRCS += $(shell find $(OSAL_PATH) -maxdepth 1 -name '*.cpp')
SRCS += $(TARGET_SRCS)

OBJS  = $(patsubst %.c, %.o,$(filter %.c,  $(SRCS)))
OBJS += $(patsubst %.cc,%.o,$(filter %.cc, $(SRCS)))
OBJS += $(patsubst %.cpp,%.o,$(filter %.cpp, $(SRCS)))
OBJS += $(patsubst %.S, %.o,$(filter %.S,  $(SRCS)))
OBJS += $(TARGET_OBJS)

TEST_SRCS  = $(shell find . -maxdepth 1 -name '*.c')
TEST_SRCS += $(shell find . -maxdepth 1 -name '*.cc')
TEST_SRCS += $(shell find . -maxdepth 1 -name '*.cpp')
TEST_SRCS += $(shell find . -maxdepth 1 -name '*.S')

TEST_OBJS  = $(patsubst %.c, %.o,$(filter %.c,  $(SRCS)))
TEST_OBJS += $(patsubst %.cc,%.o,$(filter %.cc, $(SRCS)))
TEST_OBJS += $(patsubst %.cpp,%.o,$(filter %.cpp, $(SRCS)))
TEST_OBJS += $(patsubst %.S, %.o,$(filter %.S,  $(SRCS)))

ifeq ($(TARGET_OSAL),freertos)
LIB_NAME = libosal_freertos.a
else
LIB_NAME = libosal.a
endif

$(LIB_NAME): $(OBJS)
	$(AR) rcs $@ $^

all: $(LIB_NAME) depend                       \
     test_os_task.$(TARGET_EXT)   \
     test_os_queue.$(TARGET_EXT)  \
     test_os_mutex.$(TARGET_EXT)  \
     test_os_sem.$(TARGET_EXT)    \
     test_os_timer.$(TARGET_EXT)  \
     test_os_crit.$(TARGET_EXT)   \
     test_os_ring.$(TARGET_EXT)   \
     test_os_task_cpp.$(TARGET_EXT) \
     test_os_queue_cpp.$(TARGET_EXT) \
     test_os_mutex_cpp.$(TARGET_EXT) \
     test_os_semaphore_cpp.$(TARGET_EXT) \
     test_os_timer_cpp.$(TARGET_EXT) \
     $(NULL)

test_os_task.exe: test_os_task.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_queue.exe: test_os_queue.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_mutex.exe: test_os_mutex.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_sem.exe: test_os_sem.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_timer.exe: test_os_timer.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_crit.exe: test_os_crit.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_ring.exe: test_os_ring.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_task_cpp.exe: test_os_task_cpp.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_queue_cpp.exe: test_os_queue_cpp.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_mutex_cpp.exe: test_os_mutex_cpp.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_semaphore_cpp.exe: test_os_semaphore_cpp.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_timer_cpp.exe: test_os_timer_cpp.o $(OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test: all
	./test_os_task.exe
	./test_os_queue.exe
	./test_os_mutex.exe
	./test_os_sem.exe
	./test_os_timer.exe
	./test_os_crit.exe
	./test_os_ring.exe
	./test_os_task_cpp.exe
	./test_os_queue_cpp.exe
	./test_os_mutex_cpp.exe
	./test_os_semaphore_cpp.exe
	./test_os_timer_cpp.exe

### ===== Google Test (gtest) =====

GTEST_VER = 1.14.0
GTEST_DIR = googletest-$(GTEST_VER)
GTEST_TAR = googletest-$(GTEST_VER).tar.gz
GTEST_URL = https://github.com/google/googletest/archive/refs/tags/v$(GTEST_VER).tar.gz

# Download and unpack Google Test
$(GTEST_DIR):
	@echo "Downloading Google Test v$(GTEST_VER)..."
	curl -L -o $(GTEST_TAR) $(GTEST_URL)
	tar -xzf $(GTEST_TAR)
	rm $(GTEST_TAR)

# Google Test compilation
GTEST_INCLUDES = -I$(GTEST_DIR)/googletest/include -I$(GTEST_DIR)/googletest
GTEST_OBJS = $(GTEST_DIR)/gtest-all.o $(GTEST_DIR)/gtest_main.o

$(GTEST_DIR)/gtest-all.o: $(GTEST_DIR)
	$(CPP) -std=c++14 $(GTEST_INCLUDES) -c $(GTEST_DIR)/googletest/src/gtest-all.cc -o $@

$(GTEST_DIR)/gtest_main.o: $(GTEST_DIR)
	$(CPP) -std=c++14 $(GTEST_INCLUDES) -c $(GTEST_DIR)/googletest/src/gtest_main.cc -o $@

# Wrapper compiling rules
test_os_task_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Task -DTEST_MAIN=test_os_task_main -DWRAP_C_MAIN $< -o $@

test_os_queue_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Queue -DTEST_MAIN=test_os_queue_main -DWRAP_C_MAIN $< -o $@

test_os_mutex_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Mutex -DTEST_MAIN=test_os_mutex_main -DWRAP_C_MAIN $< -o $@

test_os_sem_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Sem -DTEST_MAIN=test_os_sem_main -DWRAP_C_MAIN $< -o $@

test_os_timer_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Timer -DTEST_MAIN=test_os_timer_main -DWRAP_C_MAIN $< -o $@

test_os_ring_wrapper.o: test_gtest_wrapper.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) -DTEST_NAME=Ring -DTEST_MAIN=test_ring_main $< -o $@

# Renamed main object compilation
test_os_task_gtest.o: test_os_task.c
	$(CC) -c $(CFLAGS) -Dmain=test_os_task_main $< -o $@

test_os_queue_gtest.o: test_os_queue.c
	$(CC) -c $(CFLAGS) -Dmain=test_os_queue_main $< -o $@

test_os_mutex_gtest.o: test_os_mutex.c
	$(CC) -c $(CFLAGS) -Dmain=test_os_mutex_main $< -o $@

test_os_sem_gtest.o: test_os_sem.c
	$(CC) -c $(CFLAGS) -Dmain=test_os_sem_main $< -o $@

test_os_timer_gtest.o: test_os_timer.c
	$(CC) -c $(CFLAGS) -Dmain=test_os_timer_main $< -o $@

test_os_ring_gtest.o: test_os_ring.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) -Dmain=test_ring_main $< -o $@

# Compilation rules for new native C++ GTests
test_os_mutex_cpp_gtest.o: test_os_mutex_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_semaphore_cpp_gtest.o: test_os_semaphore_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_queue_cpp_gtest.o: test_os_queue_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_task_cpp_gtest.o: test_os_task_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_timer_cpp_gtest.o: test_os_timer_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_crit_cpp_gtest.o: test_os_crit_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

test_os_ring_cpp_gtest.o: test_os_ring_cpp_gtest.cpp
	$(CPP) -std=c++14 -c $(CFLAGS) $(GTEST_INCLUDES) $< -o $@

# Gtest binary links (C APIs)
test_os_task_gtest.exe: test_os_task_gtest.o test_os_task_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_queue_gtest.exe: test_os_queue_gtest.o test_os_queue_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_mutex_gtest.exe: test_os_mutex_gtest.o test_os_mutex_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_sem_gtest.exe: test_os_sem_gtest.o test_os_sem_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_timer_gtest.exe: test_os_timer_gtest.o test_os_timer_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_ring_gtest.exe: test_os_ring_gtest.o test_os_ring_wrapper.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

# Gtest binary links (C++ APIs)
test_os_task_cpp_gtest.exe: test_os_task_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_queue_cpp_gtest.exe: test_os_queue_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_mutex_cpp_gtest.exe: test_os_mutex_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_semaphore_cpp_gtest.exe: test_os_semaphore_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_timer_cpp_gtest.exe: test_os_timer_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_crit_cpp_gtest.exe: test_os_crit_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

test_os_ring_cpp_gtest.exe: test_os_ring_cpp_gtest.o $(OBJS) $(GTEST_OBJS)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS)

gtests: $(GTEST_DIR) \
        test_os_task_gtest.exe \
        test_os_queue_gtest.exe \
        test_os_mutex_gtest.exe \
        test_os_sem_gtest.exe \
        test_os_timer_gtest.exe \
        test_os_ring_gtest.exe \
        test_os_task_cpp_gtest.exe \
        test_os_queue_cpp_gtest.exe \
        test_os_mutex_cpp_gtest.exe \
        test_os_semaphore_cpp_gtest.exe \
        test_os_timer_cpp_gtest.exe \
        test_os_crit_cpp_gtest.exe \
        test_os_ring_cpp_gtest.exe

test_gtest: gtests
	./test_os_task_gtest.exe
	./test_os_queue_gtest.exe
	./test_os_mutex_gtest.exe
	./test_os_sem_gtest.exe
	./test_os_timer_gtest.exe
	./test_os_ring_gtest.exe
	./test_os_task_cpp_gtest.exe
	./test_os_queue_cpp_gtest.exe
	./test_os_mutex_cpp_gtest.exe
	./test_os_semaphore_cpp_gtest.exe
	./test_os_timer_cpp_gtest.exe
	./test_os_crit_cpp_gtest.exe
	./test_os_ring_cpp_gtest.exe

show_objs:
	@echo $(OBJS)

### ===== Clean =====
clean:
	@echo "Cleaning artifacts."
	rm -rf *~ .depend $(OBJS) *.o *.exe *.a $(GTEST_DIR)


### ===== Dependencies =====
### Rebuild if headers change
depend: .depend

.depend: $(SRCS) $(TEST_SRCS)
	@echo "Building dependencies."
	rm -f ./.depend
	$(CC) $(CFLAGS) -MM $^ > ./.depend;

include .depend

### Generic rules based on extension
%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@

%.o: %.cc
	$(CPP) -c $(CFLAGS) $< -o $@

%.o: %.cpp
	$(CPP) -c $(CFLAGS) $< -o $@

%.o: %.S
	$(CPP) -c $(CFLAGS) $< -o $@
